### ISSUE TITLE
[HU] Consultar información recopilada por un dispositivo

### ISSUE THREAD

**Issue by arturocs** [arturocs/crab-iot#1]
Como usuario quiero poder ver la información recopilada por un dispositivo de mi hogar, así como obtener estadísticas al respecto

**CoS:**

* Escenario: Consultar estado de un dispositivo.
  * Dado: que soy un usuario de la API de crab-iot.
  * Cuando: realizo una consulta sobre información de un dispositivo.
  * Entonces: la API me devuelve un json con dicha información.

**Notas Técnicas:**

El dispositivo al que se hace la petición podría no existir, en cuyo caso la API devolverá un error.

**Comment by Carlosma7** [comment]
Las historias de usuario no están enumeradas. Las condiciones de satisfacción (_CoS_) carecen de sentido. No veo como se relacionan las _HU_ entre sí.

**Comment by Carlosma7** [comment]
¿Las estadísticas que son? Entiendo lo de dispositivos de casa, pero no que información se supone que ha de recogerse.
