### ISSUE TITLE
Mejorar comunicación entre los plugins y el sistema

### ISSUE THREAD

**Issue by arturocs** [arturocs/crab-iot#43]
El sistema actual de intercambio de datos entre plugins y sistema central es bastante ineficiente. Actualmente la comunicación entre un plugin y el sistema principal se realiza mediante strings json, si bien este es un enfoque muy flexible, sería conveniente buscar un sistema alternativo con menos overhead. Relacionado con #6.

**Comment by arturocs** [comment]
Una opción a considerar sería usar [bincode](https://github.com/servo/bincode)

**Comment by JJ** [comment]
¿Esto es un issue o una HU? ¿A qué HU corresponde? ¿Mejorar respecto a qué? ¿Cómo sabes que lo has mejorado?

**Comment by arturocs** [comment]
Es una issue. En el sistema actual, los plugins intercambian información con el sistema mediante strings de C que contienen un json. Inicialmente lo diseñé así porque no estaba plentamente familiarizado con el sistema FFI de rust, y los strings eran una forma rápida de intercambiar datos. Sin embargo este sistema es bastante ineficiente y creo conveniente buscar alternativas.

**Comment by JJ** [comment]
Si es una issue, tienes que decir cuál es el problema. ¿Mejorar desde dónde? ¿En qué sentido está mal? ¿Cómo sabes que efectivamente ha mejorado?

**Comment by arturocs** [comment]
En la issue aclaro que quiero mejorar la eficiencia del intercambio de datos entre el sistema central y los plugins. Está mal porque no creo que una libreria dinámica deba intercambiar datos de esa forma. Aún no se si ha mejorado, la nueva implementación no está terminada. Pero cuando lo esté haré un microbenchmark

**Comment by JJ** [comment]
Si ese es el problema, ¿por qué no lo pones en el issue? ¿No dejamos claro en clase que los issues debían ser descripciones de problemas?
